version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      # This is for local development, ok to leak password.
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
